name = input("Enter your name: ")
age = int(input("Enter your age: "))
gender = input("Enter your gender: ")
city = input("Enter your city: ")
print("My name is", name,)
print("I am", age, "years old")
print("I am", gender)
print("I live in", city)
